### ISSUE TITLE
Forum Thread Link in README.MD 404'd

### ISSUE THREAD

**Issue by geratheon** [Silentine/GrimoireOfGaia#1]
I don't think this is worth a pull request, so I'll open a ticket about it:

The forum thread link in the readme is malformed, instead of this

```
* Minecraft Forum Thread: [Link](www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284614-grimoire-of-gaia-3-)
```

it should be

```
* Minecraft Forum Thread: [Link](https://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284614-grimoire-of-gaia-3-)
```

so the github markdown recognizes the link as an "absolute" path. :)

**Comment by Silentine** [comment]
Thanks! I cannot believe I forgot to try the link myself.
