### ISSUE TITLE
Disable vanish potion effect in config

### ISSUE THREAD

**Issue by KorDum** [Silentine/GrimoireOfGaia#100]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [x] I would like to propose changes.
- [ ] I would like to propose another thing.

Hello!
Can you add disable vanish potion effect (like Creep and Minotaurus) settings to the config please? Too tough.

**Comment by Xalcon** [comment]
I've had to write a mod that denies spawning of minotaurs as the players on my private server kept dying to invisible ones. We thought it was a bug until I found this issue. I dont want to be disrespectful, but why do you need additional requests for a config option?

**Comment by Azuriuz** [comment]
Please, please allow us to disable this. I also thought it was a bug and was about to report it until I saw this. People on my server keep dying to things they can't even see, and think their game is bugging out @_@

**Comment by Silentine** [comment]
Added in 1.7.0

**Comment by Azuriuz** [comment]
I know this is closed but would it be possible to have this in 1.12.2 as well?
