### ISSUE TITLE
[Suggestion]Enhance the combat books

### ISSUE THREAD

**Issue by MokoBlack** [Silentine/GrimoireOfGaia#103]
Add a left-hand effect of all books
when player hold book in left hand. book will give he buff 
And i see the staff and weapon of GOG just props. Maybe it could be used with books.
In short
Hold book in left hand and props in main hand can cast spell like witchery ~

**Comment by MokoBlack** [comment]
Image that 
a mage using sword with book

**Comment by Silentine** [comment]
The off-hand effect has already been implemented years ago. Equipping a book in the off-hand slot changes its description to reflect this.

Nah. There are mods out there that can do magic **way better** than I could ever imagine doing myself.
