### ISSUE TITLE
Some GoG mobs especially the big and strong ones are immune to “electroblobs wizardry mod” magic.

### ISSUE THREAD

**Issue by SirAron111** [Silentine/GrimoireOfGaia#107]
## Client Info
* Minecraft Version:1.12.2

* Forge Version: 14.23.5.2796 and all lower
* Mod Version: GrimoireOfGaia3-1.12.2-1.6.8.jar
* Java Version: 8 (64bit)

## Issue Description
Some GoG mobs especially the big and strong ones are immune to “electroblobs wizardry mod” magic.
When using Magic from electroblobs wizardry the mobs from grimoir of gaia are sometimes immune to it the small mobs aren’t immune but the big ones like minotaur.

## Reproduce Steps
Well that’s easy install the mods and use some magic like fire ball or magic missile or black hole whatever against the big mobs like minotaur or valkyrie etc.

**Comment by Silentine** [comment]
Tier 3 mobs (specifically the **Minotaur**, **Sphinx**, **Vampire** and the **Valkyrie**) are immune to most ranged attacks. The reason they have ranged immunity is to prevent them from being sniped from long distances as they are meant to be like _boss mobs_.

I plan to remove this immunity in the future by giving them ranged attacks when the player is out-of-reach. But for now, they cannot be harmed by them.
