### ISSUE TITLE
[SUGGESTION] Tweak all existing mobs and future mobs to use biomedict definitions for spawning

### ISSUE THREAD

**Issue by Sunconure11** [Silentine/GrimoireOfGaia#111]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [X] I would like to propose changes.
- [ ] I would like to propose another thing.

I'd like to propose the idea of all mobs spawning via biomedictionary definitions, and any other content from this mod as well, as opposed to specific biomes for some mobs (if the wiki is correct). If the wiki is correct, then the yeti is a good example of this.

**Comment by Silentine** [comment]
It currently uses biome dictionary to spawn mobs in. It is just that the biome dictionary requirement per mob have been tailored for mobs to spawn in specific biomes.
A good example of this is that mobs from this mod tend to spawn in different dimensions with different biomes from vanilla.
