### ISSUE TITLE
1.12.2 Night Vision ring strobing sky

### ISSUE THREAD

**Issue by raltus** [Silentine/GrimoireOfGaia#112]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.5.2772
* Mod Version: 1.12.2-1.6.8
* Java Version: 1.8.0.201 (64 bit)

## Issue Description
I am not sure if this is a conflict with something else I'm using or not. Normal night vision works fine. I was checking out the ore generation for the mods I'm putting together and went to grab a night vision potion in creative when I noticed the ring. I thought it would be better than drinking multiple potions while I looked around. The moment I put it on the night sky started flashing rapidly. It is fine if I'm in a cave, but on the surface at night or using spectator underground it's like the potion effect is constantly ending with a much faster visual effect even though it's still going. The inventory effects list also flashes whether it's day or night.

**Comment by Silentine** [comment]
I'll need to look into this myself. 

If I were to guess; it could be due to the duration be set at the exact moment the effect is supposed to start fading in/out.

**Comment by raltus** [comment]
I made a short video of what I am seeing and sent a pm with the unlisted link and the mod list on CurseForge.

**Comment by raltus** [comment]
I have found the conflicting mod. There is something in The Erebus that is causing the issue. I'll make a issue on their page for this. 

Apparently this isn't a first. There is a closed issue from 2016 that has the same problem. Not sure how to  do a reference link so I'll just paste it here. https://github.com/vadis365/TheErebus/issues/558

**Comment by raltus** [comment]
Fixed in latest version of The Erebus.
