### ISSUE TITLE
new version(1.6.9) breaks Baubles render

### ISSUE THREAD

**Issue by lordfriend** [Silentine/GrimoireOfGaia#120]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.5.2768
* Mod Version: 1.6.9.2
* Java Version: 1.8.0_191

## Issue Description

This issue happens after updated from 1.6.8 to 1.6.9.
All Baubles slot item render at the rear of head. not limit to the GoG item.
And the configuration of Baubles isn't working either. item will always be rendered incorrectly no matter the switch is off in baubles render config

Baubles version is 1.5.2

- Version 1.6.8

![2019-03-12_15 42 00](https://user-images.githubusercontent.com/1235614/54183315-d9dbcd00-44de-11e9-8f1e-402127594944.png)

- Version 1.6.9.2

![2019-03-12_15 16 46](https://user-images.githubusercontent.com/1235614/54183352-ef50f700-44de-11e9-8764-78ff0e53c19a.png)

**Comment by Silentine** [comment]
This issue is caused due to this line of code;
https://github.com/Silentine/GrimoireOfGaia/blob/master/src/main/java/gaia/renderer/entity/layers/LayerHeadgear.java#L62
I will fix it in the next bugfix update.

**Comment by Silentine** [comment]
Fixed in 1.6.9.3.
Not the cleanest solution, but it works.
