### ISSUE TITLE
Ender Dragon Girls ruin enderman farms

### ISSUE THREAD

**Issue by lorientalxd** [Silentine/GrimoireOfGaia#134]
Unlike Enderman, Ender Dragon girls dont target endermites so they just stay on the spawning plataform ruining the farm, currently I have to disable them to make the farms work. Either making them target endermites or making the protection talisman work on them would fix this. Thanks for the great mod btw!

**Comment by Silentine** [comment]
Too specific of an issue.
I don't make changes specifically tailored on how a player plays the game.
