### ISSUE TITLE
Minor Suggestion for Mermaids

### ISSUE THREAD

**Issue by xlea99** [Silentine/GrimoireOfGaia#137]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [X ] I would like to propose changes.
- [ ] I would like to propose another thing.

<!-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.
Just a minor suggestion, mermaids currently behave like any other mob and automatically swim up in water. I'd like to use them in an exploration pack I'm making to make underwater cities, but they just keep swimming up. Is there any way to change their AI so they behave more like underwater mobs like guardians?

**Comment by xlea99** [comment]
The suggestion information doesn't seem to be showing up, so I'll just paste it here:

Just a minor suggestion, mermaids currently behave like any other mob and automatically swim up in water. I'd like to use them in an exploration pack I'm making to make underwater cities, but they just keep swimming up. Is there any way to change their AI so they behave more like underwater mobs like guardians?

**Comment by Mrbysco** [comment]
The reason it didn't show is because you accidentally got rid of the  --> behind something. meaning it commented it all out

**Comment by Silentine** [comment]
With their current AI? No.
I could never copy the Guardian AI and get it to work in 1.12.2.
