### ISSUE TITLE
Crash server when killed by many GoG mob

### ISSUE THREAD

**Issue by zongitgud** [Silentine/GrimoireOfGaia#138]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 1.12.2 - 14.23.5.2847
* Mod Version: 1.12.2-1.6.9.3
* Java Version: java 8

## Issue Description
When killed by many GoG mob and the respawn menu pop up, the game will freeze untill the server (world) decided to shutdown itself and return the error "java.nio.channel.closedChannelException" on the screen. Which return me to the multiplayer tab even when i play in singleplayer mode. The game itself isn't crash so therefore no crash log at all

## Reproduce Steps
1. Spawn tons of GoG mob (same type is fine)
2. Gear your self so you don't die too fast, you need lot of them close together attacking you after all
3. Die
4. Freeze at respawn screen
5. Server shutdown to main menu with the said error

## Additional Information
At 1st i thought it was some minecraft bug untill i tested it with all other mod mob and well, they all work fine, even with more mob spawn. My guess is when i die they don't properly despawn which cause unresponsive and finally crash the world. When i re-join said world i will still be death but they already all despawn near my corpse

**Comment by Mrbysco** [comment]
Can you provide logs?

**Comment by zongitgud** [comment]
After 1 day trying all kind of theorys, I finally found the culprit. It's the base damage config (the one add an addition 1 heart of damage to every attack), which identify itself as non entity damage source (like potion effect). This cause an unwanted behavior, especially if many are attacking at once and cause an possible memory leak that can crash the world if you get killed by it (they all deal a same id type of damage but they are difference id source which get worse when there are too many attacking). Disabled those damage fixed it for me
