### ISSUE TITLE
Wearing Pumpkin on head can't avoid Ender Dragon Girl's aggresive

### ISSUE THREAD

**Issue by Flactine** [Silentine/GrimoireOfGaia#139]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [x] I would like to propose changes.
- [ ] I would like to propose another thing.

Look at endermen's head can anger the endermen, but wearing pumpkin on head and look at their head, won't anger them.
But even wearing pumpkin, look at ender dragon girl's head will still anger them.
Hope can avoid anger ender dragon girls by wearing pumpkin.

**Comment by Silentine** [comment]
An oversight. Will be implemented in next update.

**Comment by Silentine** [comment]
Fixed in 1.7.0
