### ISSUE TITLE
Cyan Flower Over Spawning 

### ISSUE THREAD

**Issue by LegendaryCrystalFox** [Silentine/GrimoireOfGaia#145]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.5.2847
* Mod Version: 1.7.1
* Java Version: 8 241

## Issue Description
Cyan flower mobs are over spawning in orchard biome from Biomes You Go.

## Reproduce Steps
Make Cyan flowers spawn less.

## Additional Information
https://imgur.com/a/CPS7w7H

**Comment by Silentine** [comment]
I suggest using the config to reduce the spawns. That or use a third party mod that can further control them properly (like **In Control!**).
Spawn rates are generally affected by the biome itself. Some biomes will increase the spawn rate (Desert, Plains, Ice Plains, etc.) while others reduce it (like the Jungle). 
I do not know how biomes work in **Biomes You Go**.
