### ISSUE TITLE
EntityGaiaDullahan doesnot implements AbstractHorse

### ISSUE THREAD

**Issue by TaoismDeepLake** [Silentine/GrimoireOfGaia#146]
## Client Info
* Minecraft Version:1.12.2

* Forge Version: 14.23.5.2838
* Mod Version: 1.7.1
* Java Version: 1.8

## Issue Description
It crashes with the crash log. Looks like Dullahan constructor calls on AbstractHorse but it does not implement an interface.

## Additional Information
https://pastebin.com/vQ2Q8gDR

**Comment by TaoismDeepLake** [comment]
If you need Crowflight, Idealland or Divineweapon, I can give you them as they are my mods, although I think they are irrelevant.

**Comment by Mrbysco** [comment]
Does the same happen in a normal server environment (AKA no CraftBukkit)

**Comment by TaoismDeepLake** [comment]
Sorry, I guess I will need to do some experiments to find out. We were playing on craftbukkit servers, and haven't tested otherwise.

**Comment by TaoismDeepLake** [comment]
I have experimented with this by using spawn eggs. In a normal forge server, the headless knight can be summoned with a horse successfully, whereas, in that "Cat Server" we played in, the horse won't come out (and won't crash when done manually). I guess this is not the problem of this mod.
