### ISSUE TITLE
Server crash related to GOG's Horse entity

### ISSUE THREAD

**Issue by RisingInIris2017** [Silentine/GrimoireOfGaia#153]
## Client Info
* Minecraft Version:
1.12.2
* Forge Version: 
14.23.5.2847
* Mod Version:
GrimoireOfGaia3-1.12.2-1.7.2
* Java Version: 
OpenJDK 64-Bit Server VM (mixed mode), version 1.8.0_242

## Issue Description
I run a modpack server, whose mods are listed in the attached crash report below.
Server crashes suddenly, but I checked 3 crash reports, 
and found that they are caused by similar issues related to GOG's horse.

These 3 crash reports below is generated by my server using GOG version 1.7.2, 
which is the latest version:
https://paste.ubuntu.com/p/T7W6MTpBHx/
https://paste.ubuntu.com/p/qhTqCDF9Dz/
https://paste.ubuntu.com/p/mJTHXBnW35/

My server platform is [Mohist](https://github.com/Mohist-Community/Mohist).
I have reported the same issue to Mohist's developers:
https://github.com/Mohist-Community/Mohist/issues/235

**Comment by CmdrJane** [comment]
Exact same crap happend to my Magma server, whenever GOG mob spawns on horse this resulting in a server crash

https://pastebin.com/zZGnqpfy

**Comment by Mrbysco** [comment]
Not much GrimoireOfGaia can do about it. It's CraftBukkit that's breaking
