### ISSUE TITLE
Looting Doesn't Work

### ISSUE THREAD

**Issue by AgentCPU0** [Silentine/GrimoireOfGaia#170]
I can't tell if this is actually a bug or not, but it seems that Looting has little to no effect. I'm using Tinkers, and to some extent, it has worked. But a lot of the "rare" drops aren't effected. Even rare vanilla drops are affected. Those aren't, which makes it literally impossible to get any of the important items you want

**Comment by Mrbysco** [comment]
The loot is coded in a way where what a gaia mobs drops is hardcoded. No matter if you got looting or not.
