### ISSUE TITLE
Cannot revive Holstaurus turned zombie

### ISSUE THREAD

**Issue by mrbarker2000** [Silentine/GrimoireOfGaia#171]
I kept a holstaurus in my house and added a nametag to ensure that it didn't de-spawn (just to make sure) and it got bitten into a zombie villager.  After reviving the standard way using a potion of weakness and a golden apple it revived into a normal villager instead of a holstaurus. I can confirm it is the same entity as they have the same nametag and it is a solo world.

**Comment by Silentine** [comment]
The Holstaurus and the passive/villager-like mobs in the mod are based on the vanilla villager. 
Anything that effects the villager also affects the mobs based on them. This includes zombification and villager habits.
