### ISSUE TITLE
[Bug]: 1.18.2 Dedicated Server Crash

### ISSUE THREAD

**Issue by Tyrius1** [Silentine/GrimoireOfGaia#174]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.48

### Mod version

2.0.0-alpha.1

### Java version

Java 8 333

### Issue Description

I know it's alpha. Wasn't expecting it to work just figured i'd test and share the result :)
https://pastebin.com/tJeZQtUk

**Comment by Mrbysco** [comment]
This has been fixed in [2.0.0-alpha.2.jar](https://www.curseforge.com/minecraft/mc-mods/grimoire-of-gaia/files/3824811)
