### ISSUE TITLE
[Bug]: Hilarious bug, yet akward 

### ISSUE THREAD

**Issue by RadzRatz** [Silentine/GrimoireOfGaia#177]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.18.2-40.1.25

### Mod version

1.18.2-2.0.0-Alpha.5

### Java version

Java 8 Update 51

### Issue Description

I was messing around with the mod and found out that i could equip the headgear into the Curios tab, the thing is when the headgear is equipped onto the vanilla armor tab it works well, but when equipped in the Curios tab some of them look bigger and off, this applies to all headgear

Btw i dunno if should post this as well on the Curios Issue page, kinda new in this

### Additional Information

https://imgur.com/pKH9CJ4   Vanilla Gear Tab

https://imgur.com/I4KQje3     Curios Tab

**Comment by Mrbysco** [comment]
Fixed in alpha build 6
