### ISSUE TITLE
[Bug][1.18]: Book Satchel gives blank / bugged enchanted book with no enchantments 

### ISSUE THREAD

**Issue by V972** [Silentine/GrimoireOfGaia#180]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.51

### Mod version

2.0.0-alpha.8

### Java version

default built-in Java 17 version in the official MC Launcher

### Issue Description

When opening a Book satchel, it gives you a blank enchantment book with no enchantments.
No mods with additional enchantments were installed.

Can probably be reproduced in Multiplayer.

![unknown](https://user-images.githubusercontent.com/45125685/174481435-ca7fefe9-4fcf-4189-9353-18a87c1609b9.png)

**Comment by Mrbysco** [comment]
Fixed next alpha
