### ISSUE TITLE
[Bug]: Enemies still spawning despite spawn weight = 0

### ISSUE THREAD

**Issue by Infestidos** [Silentine/GrimoireOfGaia#182]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

40.1.60

### Mod version

2.0.0 alpha 11

### Java version

Java 8 Update 333

### Issue Description

Setting weight to 0 does not disable mob from spawning.

### Additional Information

N/A

**Comment by Mrbysco** [comment]
Can you provide more information? From my testing setting the weight to 0 prevents them from being added to the biome spawns and I can't reproduce the issue

**Comment by Mrbysco** [comment]
Are you sure you restarted after changing the values?

**Comment by Infestidos** [comment]
Nvm I'm a dumbass and was editing the Common. Server config isn't showing up in Configured menu but editing manually fixed it.
