### ISSUE TITLE
[Bug]: spawnDaysPassed and spawnDaysSet config has no effect

### ISSUE THREAD

**Issue by EnderMelody** [Silentine/GrimoireOfGaia#185]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.68

### Mod version

2.0.0-alpha.15

### Java version

16.0.1

### Issue Description

the config options for spawnDaysPassed and spawnDaysSet have no effect and gaia mobs spawn as normal.

**Comment by Mrbysco** [comment]
Are you sure your world isn't older than the set amount of days?

**Comment by Mrbysco** [comment]
Also which mobs were you checking?

**Comment by Mrbysco** [comment]
Apparently there's a hand full of gaia mobs which don't check that config, 75% do.
It'll be fixed next alpha

**Comment by Mrbysco** [comment]
A new alpha has been uploaded

**Comment by EnderMelody** [comment]
tested with the new alpha 17 build in a new world, still having gaia mobs spawning. checked the config to make sure spawnDaysPassed=true and spawnDaysSet=50.
debug log:
[debug.log](https://github.com/Silentine/GrimoireOfGaia/files/9332247/debug.log)

**Comment by Mrbysco** [comment]
Could you show me the current day of your world? as the log doesn't really log mobs spawning

**Comment by EnderMelody** [comment]
had to change it to a txt from .toml
[grimoireofgaia-common.txt](https://github.com/Silentine/GrimoireOfGaia/files/9332358/grimoireofgaia-common.txt)

**Comment by Mrbysco** [comment]
Could you provide a screenshot of the f3 screen in your world? I need to know the ingame world time

**Comment by EnderMelody** [comment]
its a new world and i found a gaia mob within seconds of spawning
![2022-08-13_18 47 14](https://user-images.githubusercontent.com/12649140/184515766-172e649c-e2dc-4419-9706-2a001d2549a9.png)

**Comment by Mrbysco** [comment]
A new alpha has been uploaded and will be available shortly

**Comment by EnderMelody** [comment]
everything seems to be working now

**Comment by Mrbysco** [comment]
![image](https://c.tenor.com/XbXW81Nb7XMAAAAi/clapping-yay.gif)
