### ISSUE TITLE
[Bug]: Mobs always attacks colonist from Minecolonies

### ISSUE THREAD

**Issue by ltybcs** [Silentine/GrimoireOfGaia#187]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

40.1.57

### Mod version

GrimoireOfGaia4-1.18.2-2.0.0-alpha.13

### Java version

Java 8 update 341

### Issue Description

Mobs from Grimoire Of Gaia 4 spawns in houses from https://www.curseforge.com/minecraft/mc-mods/minecolonies and always attacks colonist NPS even when mobs neutral to players.
minecolonies-1.18.2-1.0.919-ALPHA if it helps.

**Comment by Mrbysco** [comment]
The only mobs that Grimoire of Gaia mobs attack are players, there's no code targeting colonists which means the colonists are attacking them and they're fighting back

**Comment by ltybcs** [comment]
> The only mobs that Grimoire of Gaia mobs attack are players, there's no code targeting colonists which means the colonists are attacking them and they're fighting back

Okay, I'll try to contact Minecolonies devs about this. Thanks for quick response.

**Comment by Mrbysco** [comment]
It's most likely the fact that all Gaia mobs are classified as "Monster"
