### ISSUE TITLE
[Bug]: 1.18.2 Creeps don't explode at all

### ISSUE THREAD

**Issue by SodiumZH** [Silentine/GrimoireOfGaia#189]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.68

### Mod version

2.0.0 alpha-20

### Java version

18.0.2

### Issue Description

In alpha-20 Creeps can chase the player, however when they access the player they will never explode but only stand there watching the player.

**Comment by Mrbysco** [comment]
A new jar has been uploaded and should be up shortly
