### ISSUE TITLE
Suggestion: Separate sounds for mobs?

### ISSUE THREAD

**Issue by tetsune** [Silentine/GrimoireOfGaia#19]
I'd love to be able to distinguish mobs from their sounds and I'm willing to provide royalty-free sound effects!

**Comment by DoctorWiggles** [comment]
Sounds great. I'd suggest if you haven't already, trying to get into direct contact with silentine on the forum and trying to coordinate specifics with him. Once you guys figured that out, adding the sounds to the engine is fairly simple. I'm not sure yet but we could possibly do some fancy configuration magic with it too. What versions are you planning this for?

**Comment by tetsune** [comment]
I was hoping for at the very least the upcoming 1.10 version, because I know it's a lot of work.
Eventually. Not sure how difficult it is.
I'll see if I can contact Silentine. I know he made a soundpack separate with sounds that effected the mobs jointly, but I was hoping there would be a way we could add sounds to the specific mods.

**Comment by DoctorWiggles** [comment]
Yeah, we could do that on a per mob basis. I'm not sure if you're familiar with the code but if you take a look we already manipulate most of their sounds individually.  See -> [Valkyrie Code](https://github.com/Silentine/GrimoireOfGaia/blob/pr/10/src/main/java/gaia/entity/monster/EntityGaiaValkyrie.java#L137-L153 )
While that returns one of our custom sound events, that we've registered with forge. See->
[Sounds Handler](https://github.com/Silentine/GrimoireOfGaia/blob/pr/10/src/main/java/gaia/init/Sounds.java) 
This guy defines the sound events and how they act. See-> [Sounds.json](https://github.com/Silentine/GrimoireOfGaia/blob/pr/10/src/main/resources/assets/grimoireofgaia/sounds.json) 
Which when one of the sound events are fired it will play one of our sound files here. See-> [Sounds files](https://github.com/Silentine/GrimoireOfGaia/tree/pr/10/src/main/resources/assets/grimoireofgaia/sounds )

**Comment by tetsune** [comment]
I'm can't code or anything, but I can read it and understand it c:
Okay! That's pretty cool. I'll compile a bunch of sounds and see if Silentine likes them.
