### ISSUE TITLE
[Suggestion]: 1.19.2 port?

### ISSUE THREAD

**Issue by BastardNeko** [Silentine/GrimoireOfGaia#194]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Don't know when this could possibly happen, since the 1.18.2 version is still in alpha, but was curious nonetheless.

**Comment by Mrbysco** [comment]
1.19.2 will come once the 1.18.2 version has all left-over mobs re-implemented
