### ISSUE TITLE
[Suggestion]: Wolf-like AI for friended mobs

### ISSUE THREAD

**Issue by SodiumZH** [Silentine/GrimoireOfGaia#195]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Perhaps an AI for the Wolves instead of the Iron Golems would be more suitable for friended mobs, as the latter could frequently get the mobs lost. 

In 1.18.2 version the friended mobs still walk randomly and are likely to get lost somewhere hidden (e.g. trapped into caves/ground holes, got killed at random positions, etc.). Also they may unexpectedly attack something strong and get killed when you don't know. 

Unlike the Iron Golems, Gaia mobs' HP and ATK are usually not so high and the volumes are much smaller, so the chances of getting killed or trapped are much higher. Now you have to monitor them all the time or lock them in a closed space to keep them being there. A feature for ordering them to stand or follow may be able to solve this issue. Enable binding them with Leads could also be a solution.

**Comment by AstralShadow** [comment]
I would also enjoy having a "follow" (and "stand") command for friendly mobs. :D

**Comment by Mrbysco** [comment]
This would be way to close to taming which we don't plan on doing

**Comment by SodiumZH** [comment]
> This would be way to close to taming which we don't plan on doing

I see. Is it possible to make them less likely to randomly move? For example, decreasing the chance of executing random walking goal, or decreasing the max length of random walking, so that they will take much more time to get lost.

**Comment by SodiumZH** [comment]
> I would also enjoy having a "follow" (and "stand") command for friendly mobs. :D

I'm planning to make the mobs allies for months, but don't have enough ideas about how to arrange the additional mod specifically...

**Comment by Mrbysco** [comment]
> I see. Is it possible to make them less likely to randomly move? For example, decreasing the chance of executing random walking goal, or decreasing the max length of random walking, so that they will take much more time to get lost.

Not really, I use as many vanilla goals as possible. At best I can re-arrange the priority but I doubt that'd change much

**Comment by SodiumZH** [comment]
> > I see. Is it possible to make them less likely to randomly move? For example, decreasing the chance of executing random walking goal, or decreasing the max length of random walking, so that they will take much more time to get lost.
> 
> Not really, I use as many vanilla goals as possible. At best I can re-arrange the priority but I doubt that'd change much

Probably not... Such random process is similar to something termed Brownian motion, and as time evolves the position's distribution range will expand...
 Is it possible to allow doing sth. to the mob (e.g. right click) to limit their movement range in a certain area (e.g. no more than 100 blocks away from the position right clicked)?

**Comment by SodiumZH** [comment]
> This would be way to close to taming which we don't plan on doing

Can I make taming-like behaviors on GOG4 mobs in my own mod using GOG4 mod as a dependency?
