### ISSUE TITLE
[Bug]:  Botania/ Grimoire projectile issue? Death by Grimoire magic projectile causes crash

### ISSUE THREAD

**Issue by border999** [Silentine/GrimoireOfGaia#196]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.18.2-40.2.0

### Mod version

1.18.2-2.0.0-alpha.25

### Java version

bundled java runtime

### Issue Description

was killed by one of the small desert creatures magic projectiles, and crashed upon death

### Additional Information

https://pastebin.com/h8kq74H0

**Comment by border999** [comment]
additional info, was also killed by a different creature with a projectile magic attack from Grimoire and that also caused the crash.
https://pastebin.com/a44mQw6P

**Comment by border999** [comment]
I'm pretty sure it's also bricking my player data for some reason because I keep getting "Invalid player Data" When I try to get back into a world after this crash

**Comment by border999** [comment]
https://github.com/VazkiiMods/Botania/issues/4298

**Comment by border999** [comment]
is there any update on this? if you need more info please ask. I would like to see this resolved.

**Comment by Mrbysco** [comment]
There isn't really much I can do, the crash report is barely readable due to the shear amount of mixins used. Are you able to reproduce this issue with just Botania and Grimoire of Gaia?

**Comment by border999** [comment]
testing now

**Comment by border999** [comment]
issue does not occur upon death with only grimoire of gaia, botania, and botania's dependencies. Looking to narrow down the mod in the big mix that is making magic literally crash my game. trying the magic mods first and Project mmo

**Comment by border999** [comment]
pulled forgery and debugify, crash is still occurring but crash report is halved yet again. https://gist.github.com/border999/2cae3a5c77e061cedf27ea88621e9275

**Comment by border999** [comment]
![Screenshot 2023-02-23 124459](https://user-images.githubusercontent.com/11824584/220987697-02ba2fbf-a73d-45b3-bf80-d25af75a1df1.jpg)
https://gist.github.com/border999/5818b31d650a8f4b3f01880fc0421e59
and the final answer is ArsMagica Legacy

**Comment by border999** [comment]
https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/issues/375

**Comment by Mrbysco** [comment]
Could you try out alpha 26? https://www.curseforge.com/minecraft/mc-mods/grimoire-of-gaia/files/4408957

**Comment by border999** [comment]
no longer crashing. Thank you for your time.
