### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Bluejay09** [Silentine/GrimoireOfGaia#200]
### General Info

- [ ] I am running a modpack
- [x] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.18.2 - 40.2.1

### Mod version

2.0.0

### Java version

Version 8 Update 361

### Issue Description

game crashes whenever optifine is being used

### Additional Information

[crash-2023-04-06_12.26.25-server.txt](https://github.com/Silentine/GrimoireOfGaia/files/11172669/crash-2023-04-06_12.26.25-server.txt)

**Comment by Mrbysco** [comment]
Not our problem, nothing in the crash links to Grimoire of Gaia
