### ISSUE TITLE
[Bug]: Behenders randomly give player Instance Damage effect

### ISSUE THREAD

**Issue by SodiumZH** [Silentine/GrimoireOfGaia#202]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.68

### Mod version

2.0.0-alpha.34

### Java version

Java 17

### Issue Description

On fighting against Behender, an about 15s Instance Damage effect was added which killed player very quickly.
Expectedly Instance Damage (or Instance Health) should not be added with a duration.

**Comment by Mrbysco** [comment]
A fix has been uploaded and should be available shortly
