### ISSUE TITLE
[Bug]: Chests dropping too many items

### ISSUE THREAD

**Issue by SodiumZH** [Silentine/GrimoireOfGaia#203]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.68

### Mod version

alpha.36

### Java version

Java 17

### Issue Description

On breaking a Chest, too many items were dropped if no Mimic spawned. It seems a Chest will drop only 2 in GOG3. The image below is what dropped after breaking a single Chest.
![image](https://user-images.githubusercontent.com/46860829/236622560-17865d95-7d03-48d2-91a3-c902c46fe20b.png)

**Comment by Mrbysco** [comment]
A new version has been uploaded that will fix this, it should be available shortly
