### ISSUE TITLE
[Bug]: Where are the spawn eggs for the non natural spawning mobs?

### ISSUE THREAD

**Issue by KentBill123** [Silentine/GrimoireOfGaia#209]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.20.1 - 47.2.0

### Mod version

GrimoireOfGaia4-1.20.1-4.0.0-alpha.5.jar

### Java version

Java 8

### Issue Description

The mobs such the Holstaurus, trader, creeper girl, ended girl, were sheep aren’t in the game. I’ve looked for there spawn commands and spawn eggs. They aren’t there, but you can find there tokens such as the holstarus token for some reason. How do I find these mobs spawn eggs when they don’t exist in the commands and in JEI?

**Comment by Mrbysco** [comment]
The holstaurus and weresheep haven't been re-added to the mod in 1.16+. The others that are in you can get from using an Egg Box
