### ISSUE TITLE
[Bug]: Endless loop

### ISSUE THREAD

**Issue by lSherozl** [Silentine/GrimoireOfGaia#213]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.3.5

### Mod version

Latest for 1.19.2

### Java version

Dont know?

### Issue Description

Just adding this mod to the modpack causes an endless cycle where Minecraft wont load, removing it causes the main menu to appear fine. Repeats these 2 messages again and again [22:37:40] [Worker-ResourceReload-2/ERROR]: Using vanilla stitcher implementation due to invalid loading state
and com.google.gson.JsonParseException: Model loader 'forge:separate_transforms' not found. Registered loaders: minecraft:elements
[22:37:31] [Worker-ResourceReload-2/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterAdditional to a broken mod state

### Additional Information

[latest.log](https://github.com/Silentine/GrimoireOfGaia/files/13996842/latest.log)

**Comment by lSherozl** [comment]
I will add I am using the HMAG mod which was inspired by this mod, however the owner said there were no conflicts he knew of

**Comment by Mrbysco** [comment]
There's no mention of Grimoire of gaia apart from the config files being corrected

**Comment by Mrbysco** [comment]
Also are you using optifine?

**Comment by lSherozl** [comment]
> Also are you using optifine?

No I am not using optifine

**Comment by lSherozl** [comment]
Some issues in the logs im seeing are: Configuration file C:\Users\Sheroz\AppData\Roaming\ATLauncher\instances\BetterMCFORGEBMC3\config\grimoireofgaia-client.toml is not correct. Correcting
[22:29:57] [modloading-worker-0/WARN]: Incorrect key client was corrected from null to its default, SimpleCommentedConfig:{}. 
[22:29:57] [modloading-worker-0/WARN]: Incorrect key client.genderNeutral was corrected from null to its default, false.  But ill see if I can generate another log when I try again

**Comment by lSherozl** [comment]
Im going to close this, I removed the MVS mod, or moogs voyager structures, and it loads, if you see any conflict between that and other mods in the log, please point it out to me, thank u

> Also are you using optifine?

**Comment by lSherozl** [comment]
When it does not work though I get this error don't know if it has anything to do with anything "[20/01/2024 21:40:36 p.m.] [Render thread/ERROR] 'DebugMode' is not a valid config key for config category 'advanced'.Line #5: "	DebugMode = false""
