### ISSUE TITLE
[Suggestion]: Make Grimoire of Gaia hostiles not spawn in Alex Caves' Primordial Caves

### ISSUE THREAD

**Issue by BugmanBugman** [Silentine/GrimoireOfGaia#216]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Alex's Caves recently added the "forge:no_default_monsters" to the Primordial Caves, meaning no hostile should spawn there a la mushroom biomes in vanilla. Perhaps making it so GOG hostiles don't spawn there either?

**Comment by BugmanBugman** [comment]
Check here for further info
https://github.com/iron431/irons-spells-n-spellbooks/issues/321#issuecomment-1961669844

**Comment by Mrbysco** [comment]
A new version will be available shortly that implements the suggested
