### ISSUE TITLE
[Bug][1.18.2]: Mobs with 0 base defense are invulnerable

### ISSUE THREAD

**Issue by Endgineer** [Silentine/GrimoireOfGaia#217]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.2.10

### Mod version

2.0.0-beta.9

### Java version

Java 17.0.8

### Issue Description

Since [ce6bfbf](https://github.com/Silentine/GrimoireOfGaia/commit/ce6bfbf8990ffa135d032d858d8be48aff830bcb), setting base defense to 0 causes mobs to take no damage. Probably means 0 defense is not accounted for in damage calculation; for example, [here](https://raw.githubusercontent.com/Silentine/GrimoireOfGaia/ce6bfbf8990ffa135d032d858d8be48aff830bcb/src/main/java/gaia/entity/AbstractGaiaEntity.java#:~:text=Math.min(damage%2C%20getBaseDefense())).

**Comment by Mrbysco** [comment]
Fixed next update
