### ISSUE TITLE
[Suggestion]: Balance the mobs?

### ISSUE THREAD

**Issue by sushigeek** [Silentine/GrimoireOfGaia#219]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Mob balancing does not exist. Mobs in this pack are intended if you have like prot 4 diamond gear. Zombies that are immune to fire and spam fireballs? Dude did not play test his own mod from nothing to end game. EDIT: Forgot to mention: the zombies are sprinting after me up a jump stair case. Not to mention the other stupid designs this guy thought up in his crack induced state.

**Comment by Mrbysco** [comment]
![skill issue](https://github.com/Silentine/GrimoireOfGaia/assets/9308260/e701d4b0-36fc-4782-a429-999ac0f0d54a)
