### ISSUE TITLE
[Bug]: Mob spawning with default health despite of max health being changed in config

### ISSUE THREAD

**Issue by MingkLing** [Silentine/GrimoireOfGaia#220]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.2.32

### Mod version

4.0.0 alpha8

### Java version

17.0.8

### Issue Description

Mob spawned with their default max health after modifying it in config.
I added 2x health in attributes in configuration, mob spawn with their max health doubled but their current health remains to be the default max health.
e.g.: Dryad spawned with [40/80] health, when I quadrupled the config they spawned with [40/160] health.
I tried to disable all non-essential mods and this problem persisted.

**Comment by Mrbysco** [comment]
Fixed in dev and will be included in the next builds

**Comment by Mrbysco** [comment]
Build is being generated and uploaded and should be available shortly
