### ISSUE TITLE
[Bug]: Mobs do not spawn in Taiga Biomes [1.19.2]

### ISSUE THREAD

**Issue by jchu62** [Silentine/GrimoireOfGaia#221]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.3.0

### Mod version

3.0.0-alpha.11

### Java version

17.0.7

### Issue Description

No GOG4 mobs spawn in Taiga biomes whatsoever. Tested in a modpack as well as standalone using the InControl mod to verify that no mobs are spawning. 

[1661309399] here is the seed that i tested on, version 1.19.2 gog4 + version 1.19.2 incontrol
If you check the pastebin no onis or other gog4 mobs that should spawn in taigas spawn at all

### Additional Information

https://pastebin.com/F8vkWVuy

**Comment by Mrbysco** [comment]
During what time of day were you checking?

**Comment by Mrbysco** [comment]
Build is being generated and uploaded and should be available shortly
