### ISSUE TITLE
[Bug]: Mandragoras spawn as themselves and not as blue flowers

### ISSUE THREAD

**Issue by FruitFlySlayer** [Silentine/GrimoireOfGaia#222]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.3.0

### Mod version

3.0.0-alpha.11

### Java version

17.0.7

### Issue Description

Mandragoras do not spawn as blue flowers and rather spawn as themselves.

**Comment by Mrbysco** [comment]
Build is being generated and uploaded and should be available shortly
