### ISSUE TITLE
[Suggestion]: Reduce spawnrate of flesh liches and bone knights

### ISSUE THREAD

**Issue by FruitFlySlayer** [Silentine/GrimoireOfGaia#223]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Currently, the spawn weight of flesh liches and bone knights are set to 80 in the default mod, which along with the larger caves added in the 1.18 version, leads to multiple flesh liches and bone knights attacking the player at once as opposed to the few you'd encounter in the 1.12 version, as well as their spawning crowding out other mobs. A reduction to their spawn weight would make the cave monsters more diverse compared to the flesh lich and bone knight spam we have right now.

**Comment by Mrbysco** [comment]
Build is being generated and uploaded and should be available shortly
