### ISSUE TITLE
[Suggestion]: Classify mummies and banshees as undead

### ISSUE THREAD

**Issue by tonarinoaitu** [Silentine/GrimoireOfGaia#225]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

According to the patchouli book and the official wiki the mummies and banshees are supposed to be undead, but that does not seem to be the case in the game. I would like them to be undead as it makes more sense for them to be undead.
I would also like to see wither cows classified as undead because they clearly look undead and should not be attacked by wither.

**Comment by Mrbysco** [comment]
Done (Changed Mummy and Banshee to be classified as UNDEAD)

**Comment by Mrbysco** [comment]
Wither cow is now also classified UNDEAD
