### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by German998** [Silentine/GrimoireOfGaia#228]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

more than a suggestion its a quiestion, could it be possible to disable the banshee spawn? its frustating to have her go through walls and hit me inside my home

**Comment by Mrbysco** [comment]
Yes, in 1.18 you can disable them in the config, in 1.19+ you need to make a datapack.
 https://datapack.pages.dev/biomemodifiers/disable can help you disable the biome modifier that adds them (1.19+)
