### ISSUE TITLE
[Bug]: Bone Knight rendering causing crashes on 1.21

### ISSUE THREAD

**Issue by unspunreality** [Silentine/GrimoireOfGaia#229]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.21

### Mod version

6.0.0-alpha.3

### Java version

JDK 21

### Issue Description

A bug happened! Been crashing while trying 1.21 with a bunch of mods. Looking in a certain direction on a newly created world gave a ctd.

### Additional Information

I dont fully understand crash files so I perused, checked if maybe it was various resource packs. Each time however the crash would say rending Bone Knight. I wanted to ensure that wasnt a result of a mod/resource pack. Went about removing resource packs. Checking if the other mods that came up during the CTDs were the cause(In the crash report xycraft and embeddium were mentioned but I crashed even with those disabled.) and each time is always the mention of the bone knight.

https://mclo.gs/nXWvAsz

I could be wrong and maybe some other mod is causing this but Im not proficient in understanding crash reports so Ill leave this here and hopefully you can either figure out if something changed or if Im at the wrong place with a crash report.

**Comment by unspunreality** [comment]
https://mclo.gs/Wke3Gb8

Done with just GoG. CTD. 0 other mods. 0 resource packs.

**Comment by Mrbysco** [comment]
Fixed in the next update

**Comment by Mrbysco** [comment]
6.0.0.alpha.4 is available which fixes NeoForge support past .40-beta
https://curseforge.com/minecraft/mc-mods/grimoire-of-gaia/files/5504691
