### ISSUE TITLE
How would I go about changing mob spawn rates?

### ISSUE THREAD

**Issue by hyenaheartbeats** [Silentine/GrimoireOfGaia#232]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

47.3.7

### Mod version

1.7.2

### Java version

17

### Issue Description

Too many mobs swarm the overworld at all times. The config for mob spawning is missing as well.

**Comment by Mrbysco** [comment]
Spawn rates are changed through json so you'll have to make a datapack

**Comment by hyenaheartbeats** [comment]
How would I go about making a datapack?

**Comment by Mrbysco** [comment]
I have a [general tutorial](https://datapacks.mrbysco.dev/) around constructing a datapack and an example datapack for Grimoire of Gaia with the default spawn jsons

[grimoireofgaia4-1.20.1-datapack.zip](https://github.com/user-attachments/files/16812784/grimoireofgaia4-1.20.1-datapack.zip)
