### ISSUE TITLE
Some enemy projectiles deal no damage.

### ISSUE THREAD

**Issue by ElTryken** [Silentine/GrimoireOfGaia#237]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

Neoforge 21.1.72

### Mod version

6.0.0 Alpha 7

### Java version

Java 21

### Issue Description

Projectiles from: Ant Salvager, Anubis, Arachne and Behender does not damage any entities.

![image](https://github.com/user-attachments/assets/ca5e50e6-6e28-450e-834f-ab388ce1b496)

**Comment by Mrbysco** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/grimoire-of-gaia/files/6027504
