### ISSUE TITLE
[Bug]: Accessories don't work

### ISSUE THREAD

**Issue by Partonetrain** [Silentine/GrimoireOfGaia#240]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

NeoForge 21.1.89

### Mod version

1.21.1-6.0.0-alpha7

### Java version

21

### Issue Description

Accessories do not apply effects or modifiers.
![image](https://github.com/user-attachments/assets/ae18f53d-968d-4463-b193-0e6a6f3f01e2)
It seems this method (for effect rings) is never called: 
![image](https://github.com/user-attachments/assets/a85b2d24-5f26-4cc4-8327-0381f957f7f2)
This same goes for AbstractAccessoryItem#onEquip for modifier-type accessories like Knuckles.

I would also like to bring up that the curio type tooltip (the one without the "slot" text) is unnecessary 
![image](https://github.com/user-attachments/assets/f8e1502a-b3cf-4148-b4e5-b2df452505b8)

**Comment by Mrbysco** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/grimoire-of-gaia/files/6027504
