### ISSUE TITLE
(Non issue) Older sources

### ISSUE THREAD

**Issue by vedroyder** [Silentine/GrimoireOfGaia#26]
Hi, can I see an older version of your mod made for minecraft 1.6.4?

import net.minecraft.network.NetworkManager;
import net.minecraft.network.Packet;
import net.minecraft.network.play.server.S35PacketUpdateTileEntity;

Looks like these classes were introduced in newer versions of forge which I'm not using currently >:(

**Comment by Silentine** [comment]
It is a bit late (by 6 months), but I managed to find a link.

http://www.mediafire.com/file/1jp3akolg7j8736/[1.6.4]DGrimoireofGaia2(1.8.2c).zip
