### ISSUE TITLE
[1.10.2] Issue with Ender Girls

### ISSUE THREAD

**Issue by Elvarion** [Silentine/GrimoireOfGaia#27]
- GRIMOIREOFGAIA3-1.10.2-ALPHA-1.4.7
- Forge 12.18.3.2185

Going to the End has been working just fine for the past days. But today its crashing the client the second you enter the End.

[Error Log](http://paste.atlauncher.com/view/273ff63f)

**Comment by DoctorWiggles** [comment]
Try it with the [1.4.8 version](https://github.com/DoctorWiggles/GrimoireOfGaia/releases), this should had fixed [that issue](https://github.com/DoctorWiggles/GrimoireOfGaia/issues/9).

Let me know if the upgrade resolved it.

**Comment by DoctorWiggles** [comment]
Assuming this has been resolved
