### ISSUE TITLE
Config Mob Hostility

### ISSUE THREAD

**Issue by CalebR-300** [Silentine/GrimoireOfGaia#35]
Even though I know this is meant to be an end game mod with enemies that are tough to beat, except...
I like cute mobs...
...but don't like it when they try to kill me...
...and don't feel so great killing them...
...so...
**Is it possible to make mob hostility configurable?**

Thank you for your consideration.
CalebR_300

**Comment by Silentine** [comment]
I will need to think about it. I'll give it a _50/50 chance_ of it being implementing it in the next update.

Mobs who have hostility are built with the intention of attacking the player. Turning off their hostility could mess things up. 

This would also affect **all mobs** included in the mod. Meaning a Mimic can spawn and do nothing or a Vampire can spawn Butlers that do nothing as well.

**Comment by lendrick** [comment]
So, I have a solution for this in case anyone ever reads this again.  Turn off mob spawning in Grimoire of Gaia and then use the Custom NPCs mod to set up neutral characters that use the same models and spawn randomly in the world.  You can even get into dividing them into factions so certain types will attack certain other types on sight.

**Comment by CalebR-300** [comment]
That... is a good idea.
Thanks!
