### ISSUE TITLE
Where is your changelog?

### ISSUE THREAD

**Issue by Boolyman** [Silentine/GrimoireOfGaia#40]
Your wiki site is not very user friendly.  When a patch comes out, the changelog should be front page for the first few days so we can see what changed.  I cant find it anywhere.

**Comment by DoctorWiggles** [comment]
http://the-grimoire-of-gaia.wikia.com/wiki/Changelog

If you scroll down a little on the main page it's hanging out with other icons in that content pane.

**Comment by Silentine** [comment]
If you mean _front page_ as in the _first post_ in the forum thread then I cannot. 

Editing it is a pain to deal with due to the nature of the forum. I think most modders tend to avoid editing the front page as much as possible.

If not, believe @DoctorWiggles has answered your question 👍.
