### ISSUE TITLE
An old mob comeback request

### ISSUE THREAD

**Issue by Xorbah** [Silentine/GrimoireOfGaia#47]
Is there a possibility of bringing back the Giga Knight? I really miss using it in my RPG maps, it's such a cool mob.

**Comment by Silentine** [comment]
Unfortunately it just does not fit into Minecraft. When I made GoG3 I tied my best to keep things more grounded.

I also would prefer not changing the design as it was a mob initially created by my brother for the mod. That is why I created a item called "Heart of Giga Knight" as a tribute to it.
