### ISSUE TITLE
[Suggestion] Add JEI support for satchels

### ISSUE THREAD

**Issue by Lykrast** [Silentine/GrimoireOfGaia#48]
It would be nice to have a simple JEI tab that tells you what you can get by opening a specific satchel (Egg Box, Book Satchel, Old Luggage, Iron Box...).

It could be either like [JER's dungeon tab](https://user-images.githubusercontent.com/8684850/27661975-78f975b2-5c5c-11e7-8f34-72cfcf75dc36.png) with a huge table per box, or like IC2 Scrapboxes (or like a simple machine like [ExU2's Resonator](https://user-images.githubusercontent.com/8684850/27661976-79014440-5c5c-11e7-8974-94af32071bd5.png)).

**Comment by Silentine** [comment]
Thanks to Mrbysco's contribution in the recent commit, JEI is now supported.
