### ISSUE TITLE
[Model mistake report] movement of Ender Dragon Girl's legs

### ISSUE THREAD

**Issue by dragon-evol** [Silentine/GrimoireOfGaia#52]
Found that the scale of the movement of Ender Dragon Girl's two legs are not equal ( the left is smaller ) , and after I read the codes I found that there is a mistype in
GrimoireOfGaia/src/main/java/gaia/model/ModelGaiaEnderDragonGirl.java ,
in
setRotationAngles.

Hope it's fixed in the next version! ( From a lover of dragons )
![enderdragongirl](https://user-images.githubusercontent.com/36005678/35634312-59357d0e-06e6-11e8-8e12-4ed04270fd9a.png)

**Comment by Silentine** [comment]
Weird that I never noticed that. Thanks for the heads up!
