### ISSUE TITLE
Possible mob spawner issue

### ISSUE THREAD

**Issue by Bargonzo** [Silentine/GrimoireOfGaia#54]
After a fair amount of testing, I may have noticed a bug related to vanilla mob spawners. Some mobs do not appear to spawn from vanilla spawners, sometimes in spite of being in the proper biome or at the proper Y-level (I based that off of the wiki).

I've tested both your version of the mod and DoctorWiggles's (as posted on the MCForums thread) and put my results on Google Sheets. Here's the link (https://docs.google.com/spreadsheets/d/1DG21b5zzFR03qsUhHs_AUMKC1qUrv8qoq9pesBmU6T8/edit?usp=sharing)

Feel free to disregard if the issue is related to Vanilla spawners.

**Comment by Silentine** [comment]
Thanks! Especially for creating a spreadsheet on it

I will look into this in the recent commit to check if this issue is still present.

**Comment by Silentine** [comment]
The issue may have been resolved by now after the amount of changes/releases since this has been reported.
