### ISSUE TITLE
[enhancement] Male Mobs

### ISSUE THREAD

**Issue by Aaron082001** [Silentine/GrimoireOfGaia#55]
Hi this is not issue but can you add male mobs because its really unrealistic to see that all mobs is girls.But overall your mod is awesome

**Comment by Silentine** [comment]
Thanks!

Thing is when I originally made this mod in 2012 there were no female mobs available in most (if not, **all**) mob mods. This mod was originally meant to compliment mods that had no female mobs.

Will I be adding male equivalents of the current female mobs? **Probably not**. I do plan to add more male mobs in the future though, just not male equivalents (such as a male Dryad, etc.)
