### ISSUE TITLE
Source code doesn't compile without baubles api

### ISSUE THREAD

**Issue by Azarius1799** [Silentine/GrimoireOfGaia#56]
I don't know if I missed something, but, when I download the source code and use "gradlew build" it spews all kinds of things about not having baubles api. I am super new to the whole modding thing so I might have missed something to cause this issue.

**Comment by Silentine** [comment]
Sorry for the inconvenience.

The last build required the Baubles API to be present in the folder when the command is executed. In the latest commit this issue should be resolved and it no longer needs Baubles installed.
