### ISSUE TITLE
Dedicated server crash when hitting a minotaurus

### ISSUE THREAD

**Issue by Febilian** [Silentine/GrimoireOfGaia#65]
https://gist.github.com/Febilian/cf5abcf953bb4b94790de4d9a4e61770

To clarify, I'd been whacking at it for a while(fairly early game, so a stone sword), and I think it may be possible it had finally gotten to low enough health to attempt special behavior(buff, summon minotaur, whatever), but as soon as I landed my next hit, I got kicked to the title screen and the server had crashed.

Using the most recent version from Curseforge(the 1.12.2 beta 2 file).

Let me know if there is more information I can provide.

UPDATE: The minotaurus in question now causes the server to crash immediately after the world is loaded.

**Comment by Mrbysco** [comment]
Could you provide your GrimoireOfGaia config that the server/clients use?

**Comment by Mrbysco** [comment]
(Accidentally clicked the assign button instead of label. Don't mind that message)

**Comment by Febilian** [comment]
This is what I'm using:

https://gist.github.com/Febilian/6aa0cb30b68d8f0f24949b5cafc99838

I'm using In Control to manage where the mobs spawn, which is why all of those options are at 0.

Now that it's been said, I wonder if putting the tier 3 mobs at 0 is what caused it... even though they are supposed to spawn indirectly anyways, I thought?

**Comment by Febilian** [comment]
Okay, yeah, I'm fairly certain this was caused by the config "tier 3 chance" being set to 0 by accident while the other config option that tries to make them spawn was still true.

I'd suggest some kind of internal failsafe to present user stupidity with the config from breaking the game...

**Comment by Silentine** [comment]
Noted. 

I will add an additional condition to check if the tier 3 chance is set to 0 in the next update.

**Comment by Silentine** [comment]
Fixed in 1.6.0-beta3.
