### ISSUE TITLE
Hostile mobs spawn in mushroom island

### ISSUE THREAD

**Issue by skydark** [Silentine/GrimoireOfGaia#69]
Version: GrimoireOfGaia3-1.12.2-1.6.0-beta3
I have found many red circles in journey map and try to figure out what happened. This is what I see before I die. I am pretty sure they are not wandering from other biomes.
![Imgur](https://imgur.com/HRuRYkW.jpg)

**Comment by Silentine** [comment]
They can spawn in the **Beach** biome.

Mobs who spawn in the Beach biome always spawn underground though. If the red circles where actually in the island and not around it then that is an issue.

**Comment by skydark** [comment]
They can suddenly spawn in the center (underground) of my mushroom island basement when I travel back. Also even from this screenshot you can see that (under the mini map) this biome is MushroomIsland but not beach or MushroomIslandShore (which should also be peaceful).

**Comment by Silentine** [comment]
Which mobs spawn there? Is it the [Ocean](http://the-grimoire-of-gaia.wikia.com/wiki/Category:Ocean) mobs? [Underground](http://the-grimoire-of-gaia.wikia.com/wiki/Category:Underground) mobs? Or **both**?

**Comment by skydark** [comment]
I have only found Mermaid and Sahuagin yet. So it is possible both.

**Comment by Silentine** [comment]
That means **Ocean** mobs are spawning in underground the MushroomIsland biome. 

I will add more restrictions to their spawn conditions in the next update.

**Comment by skydark** [comment]
Double checked and tested. I guess they are spawned in MushroomIslandShore because this biome also has a biome type of BEACH.
(And why can they spawn in the middle of an mushroom island? Because there are several tiny sized MushroomIslandShores inside the island, even hundred meters to the nearest ocean...)

**Comment by Silentine** [comment]
Minecraft biome generation has a few issues.  The River biome for example can be found in areas where there is no water even present.

The fix will be implemented in 1.6.0-beta**5**.

**Comment by Silentine** [comment]
Fixed in 1.6.0-beta5.
