### ISSUE TITLE
Crashes in the End

### ISSUE THREAD

**Issue by moonrushy** [Silentine/GrimoireOfGaia#73]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.4.2759
* Mod Version: 1.12.2-1.6.0-beta4
* Java Version: 1.8.0_181

## Issue Description
Constant crushes in the End. Most likely, it is connected with the _Ender Dragon Girl_ spawns. Also, I'm unable to spawn her using the egg.

## Reproduce Steps
Enter the End and wait until the game tries to spawn Ender Dragon Girl. It gives me instant crash.

## Additional Information

Crashlog: [https://pastebin.com/8hUp8A6S](https://pastebin.com/8hUp8A6S)
Maybe the same problem: [https://github.com/Silentine/GrimoireOfGaia/issues/27](https://github.com/Silentine/GrimoireOfGaia/issues/27)

**Comment by Mrbysco** [comment]
#27 Is related to rendering the Ender Dragon Girl which isn't the issue in your crash.

**Comment by Silentine** [comment]
You are right; they cannot be spawned from eggs. It seems to be related to to [this line of code](https://github.com/Silentine/GrimoireOfGaia/blob/master/src/main/java/gaia/entity/monster/EntityGaiaEnderDragonGirl.java#L160).

Weird, I do not remember modifying this mob recently. I will see what I can do.

**Comment by moonrushy** [comment]
Thanks!

**Comment by Silentine** [comment]
Thanks for taking your time to report this bug.

I managed to fix it; it is meant to be (dataManager.**register**), not (dataManager.**set**). I still can't remember touching this recently.

The fix will be implemented in 1.6.0-beta5.
