### ISSUE TITLE
Dryads AI causing server crash

### ISSUE THREAD

**Issue by kenny2810** [Silentine/GrimoireOfGaia#78]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.4.2757
* Mod Version: 1.6.0 - Beta 5
* Java Version: 8 Update 181

## Issue Description
The server crashes due to a java null pointer exception in the Dryad's AI. I suspect it might be  a corrupted Dryad but can't verify it without crashing the server. 

## Reproduce Steps
Load up server.
Wait a while until a Dryad spawns. 
The server will keep crashing repeatedly. 

(Sorry I can't be more help on this, the Dryad in question couldn't be located without crashing the server each time)

## Additional Information

Crash Report:
https://pastebin.com/q4LYmHMv

Also important to note I tried a temporary fix by setting their spawn rate to 0 in the config. It did not work, as they kept spawning. When I tried using the kill command they would not outright die, instead only lose a portion of HP.

**Comment by Silentine** [comment]
I am not quite sure what is causing this issue. It could be a mod conflict, or the mod itself. I am unfamiliar with handling server issues.

From what I have researched so far you have a **ticking entity** issue which usually happens to dedicated servers. It can be resolved using the **NBTExplorer** program to remove the entity from the world if you cannot reach it yourself.

If you want to kill them using the /kill command you need to set the _Base Damage Cap_ (in the config) to 1.

**Comment by kenny2810** [comment]
Ok thank you for the heads up! Will try your suggestions :)
