### ISSUE TITLE
Odd rendering crash with extreme hills biome mobs.

### ISSUE THREAD

**Issue by vagaprime** [Silentine/GrimoireOfGaia#8]
had a player ona server hosting my pack come to me about a crash to desk top. looing at what we could find about the error before the crash in the fml log it appears to be caused by the game trying to render the Gryphon and Valkyrie. The player did admit to using optifine and that removing optifine finaly stoped the crashes. Here is a link to the last part of the FML log where the error is shown.

http://pastebin.com/FSGd94XZ

I would like to note that most players use optifine to help increase FPS in modded minecraft or for shadders

**Comment by DoctorWiggles** [comment]
Could you post your full modlist and what version this is for? I couldn't get it to break with the newest Gog and Optifine by themselves for 1.8.9.

**Comment by vagaprime** [comment]
the pack in on mc 1.7.10

Gog 1.7.10-1.2.7 and optifine 1.7.10 HD_U_D6

mod list
https://docs.google.com/spreadsheets/d/13WVyKMBs3wSDexM8u18fbpin77VEwHLOjXdLmtoNsRU/edit#gid=1842227799

**Comment by Silentine** [comment]
This issue has been open for 2 years. It is unlikely that I will ever return to modding for 1.7.10.
