### ISSUE TITLE
[Suggestion] Dimension spawning blacklist

### ISSUE THREAD

**Issue by Mike-U5** [Silentine/GrimoireOfGaia#80]
## SUGGESTIONS
- [X] I would like to propose new content.
- [ ] I would like to propose changes.
- [ ] I would like to propose another thing.

## SUGGESTION INFORMATION
GOG mobs seem to happily spawn in certain modded dimensions where they are not supposed to spawn.
I would like to request a configurable blacklist of dimensions where Grimoire of Gaia mobs will never spawn.

**Comment by pirone2** [comment]
Seconding this

**Comment by Silentine** [comment]
Sadly, I am incapable of programming this in. 

This issue has existed since the Forge BiomeDictionary was introduced. I am not even sure if it is possible to set spawns based on Biomes and not BiomeDictionary tags.

**Comment by Silentine** [comment]
In the mean time, I suggest using a mod called **In Control!**. It was suggested in the forum as a temporary solution to this issue.

**Comment by Mrbysco** [comment]
I've added a dimension blacklist to the mod.

**Comment by Silentine** [comment]
Implemented by **Mrbysco** in (1.6.0).
