### ISSUE TITLE
Conflict with Thaumcraft

### ISSUE THREAD

**Issue by Kinkypie** [Silentine/GrimoireOfGaia#87]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.4.2715
* Mod Version: 1.6
* Java Version: 8u91

## Issue Description
Game won't launch. There appears to be and exception regarding the way thaumcraft handles it's aspects and Grimiore.

## Reproduce Steps
Installing Grimiore via the curse/twitch launcher or manually both trigger the crash when you would try to run the game.

## Additional Information
https://pastebin.com/AU2RwB0B

**Comment by Mrbysco** [comment]
You're using an old version of Thaumcraft. Grimoire of Gaia is build against Thaumcraft 6.1.BETA22

**Comment by Kinkypie** [comment]
Forcing the twitch/curse launcher to update to Thaumcraft beta 22 fixed the issue. Closing.
