### ISSUE TITLE
Invisible Minotaurus

### ISSUE THREAD

**Issue by KorDum** [Silentine/GrimoireOfGaia#89]
## Client Info
* Minecraft Version: 1.12.2
* Forge Version: 14.23.4.2764
* Mod Version: 1.6.3
* Java Version: 1.8.181

## Issue Description
Minotaurus is invisible, exception in console, see below.

## Reproduce Steps
I'm not sure I can say steps... I'm not using Optifine.

## Additional Information
https://gist.github.com/KorDum/9071d29e327a20b9d9ff2b8e474ce3b6

**Comment by KorDum** [comment]
Yeah me too

**Comment by Silentine** [comment]
I cannot recreate this issue. Here is a screenshot of of both the melee and ranged variants spawned naturally;

![2018-10-11_18 24 47](https://user-images.githubusercontent.com/9960912/46798113-92acad00-cd83-11e8-9a6b-94e77ed56147.png)
_(A skyblock map with the Minotaurus spawn rate set to 1,000,000)_

The Minotauruses firing at nothing is an archer bug. I'm not even sure how to recreate it, it's random from what I have observed so far.

**Comment by KorDum** [comment]
Maybe forge 2764 is buggy... I try to test in 2769.

**Comment by Silentine** [comment]
I recently had to screencap the Minotaurus (using the latest version, 1.6.7) for their wikia entry and they still appeared normally. 

I assume that this issue is resolved due to the lack of response after a week.
