### ISSUE TITLE
Monsters can interact more with players. 

### ISSUE THREAD

**Issue by MokoBlack** [Silentine/GrimoireOfGaia#92]
## SUGGESTIONS
- [x] I would like to propose new content.
- [ ] I would like to propose changes.
- [ ] I would like to propose another thing.

<!-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.
## SUGGESTION INFORMATION

the monsters are so stronger and so cool  , is good if they can help steve to fighting

**Comment by Silentine** [comment]
Thanks for your input.

Some of them now do though. A few selected mobs can attack hostile mobs (similar to an Iron Golem). Except they have no real changes in behavior or complicated AI (such as a Wolf).

Taming mobs (depending on how you define _taming_) though will not be happening. Mainly for 3 reasons:
- Difficult to implement without rewriting a ton of base code
- I have no idea how to
- I hate companions/allies that have their own AI. It is difficult to execute properly.
