### ISSUE TITLE
Ticking entity crash when around Minotaurus.

### ISSUE THREAD

**Issue by kradlyn** [Silentine/GrimoireOfGaia#93]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.5.2768
* Mod Version: 1.6.5
* Java Version: 1.8.0_111 64 bit

## Issue Description
Server crashes whenever a Minotaurus is spawned

## Reproduce Steps
Spawn a Minotaurus

## Additional Information
https://pastebin.com/w0pxVWE3 <--crash log

Changed config for Minotaurus spawn to zero and ran fine.  Teleported to an area that had Minotaurus before the crash and server crashed upon arrival.  Downgraded back to 1.6.4 and no crash around them.

**Comment by cursinorock** [comment]
same here

**Comment by Silentine** [comment]
This is a **ticking entity issue**. It is usually caused when **upgrading versions** on dedicated servers. (Refer to issue #78 for reference).

The only way to solve this is to remove the entity in question.

I cannot recreate this issue. I managed to spawn them in both using a Monster Egg and naturally;
![2018-10-11_18 24 47](https://user-images.githubusercontent.com/9960912/46798427-79f0c700-cd84-11e8-8c9f-6b75b8b0290d.png)
_(A skyblock map with the Minotaurus spawn rate set to 1,000,000)_

**Comment by cursinorock** [comment]
maybe my report will help
[crash-2018-10-10_22.35.52-server.txt](https://github.com/Silentine/GrimoireOfGaia/files/2470104/crash-2018-10-10_22.35.52-server.txt)

**Comment by Silentine** [comment]
Please read [the comment above](https://github.com/Silentine/GrimoireOfGaia/issues/93#issuecomment-428907294); it is a **ticking entity** issue. 

You need to remove the mob in question from the chunk it is located in.

**Comment by Silentine** [comment]
This issue should have been resolved with the 1.6.6 update and further concluded with the 1.6.7 update.
