### ISSUE TITLE
Siren cause crash: EntityGaiaSiren.isTarget()Z is abstract

### ISSUE THREAD

**Issue by KorDum** [Silentine/GrimoireOfGaia#96]
## Client Info
* Minecraft Version: 1.12.2
* Forge Version: 14.23.5.2769 
* Mod Version: 1.6.6
* Java Version: 1.8 r181

## Issue Description
Spawn Siren work fine. But if Siren sees player, there will be a crash.

## Additional Information
https://gist.github.com/KorDum/e1c3a331095fd643af09d3e1ff13b5a8

**Comment by Silentine** [comment]
Thanks for reporting this issue. Will be fixed in the next update which should be very soon.

**Comment by Silentine** [comment]
Removed `isTarget()`. This issue should be resolved.
