### ISSUE TITLE
1.12.2-1.6.7 Possible conflict with Coherent Villages

### ISSUE THREAD

**Issue by kreezxil** [Silentine/GrimoireOfGaia#99]
https://pastebin.com/KwUpQTxe

original report filed at https://github.com/TheExceptionist/Coherent-Villages/issues/35

**Comment by Silentine** [comment]
_Please fill in the correct bug report form next time._

I checked the report you filed over in the Coherent-Villages GitHub and the author commented an hour later after your post there that he fixed it.
